name = "solana-explorer"
compatibility_date = "2025-05-01"

# Add this line to point to the worker script
main = "./.next/server/edge-runtime-webpack.js"

# Keep your site configuration
[site]
bucket = "./.next/static"

# Build configuration
[build]
command = "npm run build"